title: Keep Your Options
description: A learning journey about investment options.
url: "https://www.keepyouroptions.com"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:title.html

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

show_excerpts: true
