title: Keep Your Options
tagline: A running ledger of learning options trading.
description: A learning journey about investment options.
url: "https://www.keepyouroptions.com"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:title.html

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

show_excerpts: true
